### ISSUE TITLE
Small modifications for Guzzle ~6.0

### ISSUE THREAD

**Issue by lrobi2014** [WhatDaFox/Codeception-Mailtrap#11]
Hi @foxted 
So I included this via composer to use in my testing environment, and I found some tweaks that need to be made for it to work with Guzzle 6:
1. The way the Client Guzzle object is constructed - I am suggesting:

``` php
$this->client = new Client([
            'base_uri'        => $this->baseUrl,
            'version'         => $this->config['version'],
            'headers' => [
                'Api-Token' => $this->config['client_id'],
            ],

        ]);
```
1. I don't think the send() and json() should be used anymore
2. Since these two functions deprecated in Guzzle 6, the calls made to the api need to be adjusted. For example, fetchLastMessage could probably look like:

``` php
$messages = $this->client->get("inboxes/{$this->config['inbox_id']}/messages")->getBody();
return $messages;
```

This returns a json string of the body response.
1. On the home page - you could update the sample functional.suite.yml to the following:

``` php

class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - \Helper\Functional
        - Asserts
        - Laravel5:
            environment_file: .env.testing
            cleanup: true
        - Mailtrap:
            client_id: ADD_YOUR_API_TOKEN_HERE
            inbox_id: ADD_YOUR_INBOX_ID_HERE
```

I'm not sure if these are unique to me, but I am still sharing in case it helps someone else

**Comment by foxted** [comment]
Merged. Thank for the PR ;)

**Comment by lrobi2014** [comment]
Hahaha No problem :)
