### ISSUE TITLE
Error with _after() must implement interface Codeception\TestCase

### ISSUE THREAD

**Issue by fehrlich** [WhatDaFox/Codeception-Mailtrap#13]
the module works fine but if i use the module in my acceptance tests i get the error:

`Argument 1 passed to Codeception\Module\Mailtrap::_after() must implement interface Codeception\TestCase, instance of Codeception\Test\Cept given, called in ...Codeception/Subscriber/Module.php on line 68 and defined`

**Comment by foxted** [comment]
Will look into it :+1:

**Comment by foxted** [comment]
Will be fixed once fixing https://github.com/WhatDaFox/Codeception-Mailtrap/issues/15
