### ISSUE TITLE
Delay in mail delivery

### ISSUE THREAD

**Issue by ademola-raimi** [WhatDaFox/Codeception-Mailtrap#18]
In some cases, I have a problem with the package only checking the inbox once, and so if there is any delay in delivery, the email may not have arrived by the time it checks for it. Any ideas how to fix this?

**Comment by foxted** [comment]
Not sure I understand your issue, but I think Mailtrap is pretty responsive to receive the emails, unless you are using a queue to send the email. In which case, I would consider deactivating the queue during testing to fire the email immediately.

**Comment by ademola-raimi** [comment]
Thanks
