### ISSUE TITLE
Codeception not recognize the module

### ISSUE THREAD

**Issue by ulver2812** [WhatDaFox/Codeception-Mailtrap#20]
Hi, I'm trying to install and use this module but it seems not work, after the installation procedure I get error messages when I run an acceptance test.

This is my composer.json

`}
    "require-dev": {
        "codeception/codeception": "^2.3",
        "whatdafox/codeception-mailtrap": "^1.2"
    },
    "require": {
        "fzaninotto/faker": "^1.7"
    }
}`

This is the acceptance.suite.yml file (*asterisks for privacy):

`actor: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance

modules:
    enabled: [Filesystem, FunctionalHelper, Db, Mailtrap]
    config:
        Mailtrap:
            client_id: '********************'
            inbox_id: '*******'

paths:
    envs: tests/_envs`

I ran the command "codecept build" but it seems that it not added any method, this is the log:

`Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
\AcceptanceTester includes modules: \Helper\Acceptance
 -> FunctionalTesterActions.php generated successfully. 0 methods added
\FunctionalTester includes modules: \Helper\Functional
 -> UnitTesterActions.php generated successfully. 0 methods added
\UnitTester includes modules: Asserts, \Helper\Unit
`

This is my acceptane Cest:

`<?php

use Faker\Factory as FakerFactory;

class UserAccountCest
{
	private $faker;
	public function __construct()
	{
		$this->faker = FakerFactory::create('it_IT');
	}

    public function _before(AcceptanceTester $I)
    {
    }

    public function _after(AcceptanceTester $I)
    {
    }

    // tests
    public function checkEmail(AcceptanceTester $I){
		$I->fetchLastMessage();
    }
}`

And finally the error that I get:
"[RuntimeException] Call to undefined method AcceptanceTester::fetchLastMessage"

I think that the issue is releated to the "codecept build" command that not add any module methods to the correct class. 
Please can you help me?

Thanks 
Regards

Umberto

**Comment by foxted** [comment]
Did you try adding the module in the Acceptance config?

```
actor: AcceptanceTester
modules:
    enabled:
         - \Helper\Acceptance
         - Mailtrap
```

**Comment by ulver2812** [comment]
Thank you very much, this was the problem, I forget to add the module -_-
