### ISSUE TITLE
Modules Extends import

### ISSUE THREAD

**Issue by yepzy** [WhatDaFox/Codeception-Mailtrap#22]
Hi @foxted,

I update my packages and I see that the test have fail with this error
`PHP Fatal error:  Class 'Codeception\Module\Module' not found`

And I see that you remove the import of the `Module` in the commit http://bit.ly/2Hc4PRI

**Comment by polevaultweb** [comment]
@foxted yep seeing the same issue. Adding the use statement back in works.
