### ISSUE TITLE
Class 'Codeception\Module\Module' not found in vendor/whatdafox/codeception-mailtrap/src/Mailtrap.php on line 33

### ISSUE THREAD

**Issue by funkh** [WhatDaFox/Codeception-Mailtrap#33]
I've just checked this module with codeception v2.4.1, but i get an error Class 'Codeception\Module\Module' not found in vendor/whatdafox/codeception-mailtrap/src/Mailtrap.php on line 33 when running 'codecept build'
The Mailtrap class uses the namespace Codeception\Module, so the extended codeception abstract Module class without full namespace resolves to Codeception\Module\Module, which does not exist.
Solution 
```
class Mailtrap extends \Codeception\Module
{
```

**Comment by jakeBarwell** [comment]
Also causing me issues :+1:

**Comment by jimtaylor123** [comment]
I am also getting the same error. Looks like Mailtrap changed their site structure since https://mailtrap.io/api/v1/ now goes to a 404 page.

**Comment by foxted** [comment]
Should be fixed by #36. Keep me updated if not the case.
