### ISSUE TITLE
Adding some use examples in the readme

### ISSUE THREAD

**Issue by apsdsm** [WhatDaFox/Codeception-Mailtrap#42]
First off, this is such a great library, thank you so much for providing it. I'm doing some testing on a legacy system that fires off a lot of emails, and it's proving to be invaluable for checking that stuff all works as it should.

The only issue I've had so far is that there's no real docs on how to use the library in your tests. I know that it's all pretty self evident if you spend more than a few minutes with it installed, or even give the source code a fleeting glance, but maybe it would make the module a little friendlier if there were a few examples on how it works in the readme.

I know that's a pretty annoying ask, so if it you're ok with it, I'd be happy to write a few use examples and submit as a pull request to the readme.

Thanks again for making this module available.

**Comment by foxted** [comment]
That's a good idea, any PR is welcome :)

**Comment by apsdsm** [comment]
OK! I'll spend some time on this then!
